### ISSUE TITLE
gitlit isn't recognizing repository as a git lfs repository

### ISSUE THREAD

**Issue by cjddmut** [S2-/gitlit#4]
Possibly things aren't set up correctly but I'm not sure what to check against. LFS is definitely installed and part of the repository.

![image](https://user-images.githubusercontent.com/2998383/78181356-12678500-7419-11ea-9b2d-935ae9e5e728.png)

**Comment by 5im-0n** [comment]
Is `git ls-files` returning something?

**Comment by xehonk** [comment]
I have the same issue. git ls-files is returning a list of files.

```
$ git lfs ls-files
28b330c20a * gradle/wrapper/gradle-wrapper.jar
...
```

I do however get an error in the output of gitlit:
```
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:357:14)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20) cmd: 'git ls-files | git check-attr --stdin lockable' }
```

**Comment by jonaskew** [comment]
I had the same issue, and bumping the maxBuffer size up in main.js line 18 fixed it.  I think it was simply the number of files in LFS overflowing the buffer.

**Comment by 5im-0n** [comment]
Thanks. Currently the `maxBuffer` is 1MB. I bump it to 10MB. Hopefully that's enough for everyone. Let's see if more issues come in.

fixed in 9c26b8fb1

**Comment by xehonk** [comment]
It's enough for my repository. Thanks!

**Comment by cjddmut** [comment]
Still isn't working for me.

I'll try to very quickly set up an environment to build out to see if increasing further fixes it for me. Though this is not really my domain area so may not get to it quick enough before jumping back to work.

Maybe a future feature for settings? This might be a pretty natural thing to put in one :)

**Comment by cjddmut** [comment]
Well for me it looks like locking isn't working on BitBucket :(

**Comment by 5im-0n** [comment]
> Well for me it looks like locking isn't working on BitBucket :(

gitlit just uses the underlying git command from the environment. There is nothing specific in gitlit that could not work. It's just executing git.

**Comment by cjddmut** [comment]
https://confluence.atlassian.com/bitbucket/current-limitations-for-git-lfs-with-bitbucket-828781638.html#CurrentlimitationsforGitLFSwithBitbucket-GitLFSlockisnotsupportedonBitbucketCloud
